[package]
name = "bevy_dojo"
version.workspace = true
edition = "2024"

[dependencies]
bevy.workspace = true
bevy_enhanced_input.workspace = true
log.workspace = true
starknet.workspace = true
tracing.workspace = true

[lints]
workspace = true
