[package]
cairo-version = "=2.10.1"
name = "elysium_descent"
version = "1.5.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.5.0" }
dojo_inventory_mgmt = { path = ".." }
dojo_survivor = { path = ".." }

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]

[dev-dependencies]
cairo_test = "=2.10.1"
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.5.0" }
