[package]
cairo-version = "=2.10.1"
name = "elysium_descent"
version = "0.0.1"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[dependencies]
achievement = { git = "https://github.com/cartridge-gg/arcade", tag = "v1.6.0" }
death_mountain = { git = "https://github.com/okhaimie-dev/death-mountain.git", rev = "697fd77" }
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.6.0" }
openzeppelin_token = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v1.0.0" }
openzeppelin_introspection = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v1.0.0" }
starknet = "2.10.1"
tournaments = { git = "https://github.com/okhaimie-dev/tournaments.git", rev = "f7b6897" }

[dev-dependencies]
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.6.0" }
cairo_test = "2.10.1"

[[target.starknet-contract]]
build-external-contracts = [
    "dojo::world::world_contract::world",
    "achievement::events::index::e_TrophyCreation",
    "achievement::events::index::e_TrophyProgression",
    "tournaments::components::models::game::m_GameMetadata",
    "tournaments::components::models::game::m_TokenMetadata",
    "tournaments::components::models::game::m_GameCounter",
    "tournaments::components::models::game::m_Score",
    "tournaments::components::models::game::m_Settings",
    "tournaments::components::models::game::m_SettingsDetails",
    "tournaments::components::models::game::m_SettingsCounter",]

[profile.slot]
