[package]
name = "dojo_survivor"
version.workspace = true
edition.workspace = true

[dependencies]
dojo.workspace = true

[dev-dependencies]
dojo_cairo_test.workspace = true
cairo_test.workspace = true

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]
